spring:
  application:
    name: forohubapi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: <DATASOURCE_URL>
    username: <DATASOURCE_USER>
    password: <DATASOURCE_PASSWORD>
server:
  error:
    include-stacktrace: never